### ISSUE TITLE
Cannot read property 'props' of undefined with simple fusion app example

### ISSUE THREAD

**Issue by romaxa** [uber/nebula.gl#154]
#### Describe the bug
Nebula getChildContext get called before component mount and crashes in fusion app 

#### Actual Result
```
TypeError: Cannot read property 'props' of undefined
    at NebulaReact.props [as getChildContext] (/test-nebula-compat-fusion/node_modules/nebula.gl-react/src/lib/nebula-react.js:41:7)
    at getChildContext (/test-nebula-compat-fusion/node_modules/fusion-react/src/async/prepare.js:26:41)
    at renderCompositeElementInstance (/test-nebula-compat-fusion/node_modules/fusion-react/src/async/prepare.js:94:14)
    at 
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

#### Expected Result

Nebula should handle getChildContext call before mount

#### Reproduce Steps
Steps to Reproduce:

yarn create fusion-app demo
yarn add deck.gl react-map-gl nebula.gl
yarn dev

Add simple nebula to main page

test repo located here: [fusion-app-nebula](https://github.com/romaxa/fusion-app-nebula)

```
      <Nebula ref={nebula => nebula} viewport={{width: 800, height: 600}} layers={[]}>
        <InteractiveMap />
      </Nebula>
```

#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

**Comment by georgios-uber** [comment]
Thanks @romaxa for fixing this.
