### ISSUE TITLE
Errors when using DrawPolygonMode and DrawRectangleMode  @nebula.gl/layers@1.0.2-alpha.1 / @nebula.gl/layers@1.0.2

### ISSUE THREAD

**Issue by echo292** [uber/nebula.gl#904]
Errors when using DrawPolygonMode and DrawRectangleMode  **@nebula.gl/layers@1.0.2-alpha.1 / @nebula.gl/layers@1.0.2**

This seems like a lib mismatch however I'm not clear if the function signature changed at some point.

Uncaught runtime errors:
×
ERROR
(0 , _rewind.default) is not a function
TypeError: (0 , _rewind.default) is not a function
    at DrawPolygonMode.rewindPolygon (http://localhost:3000/static/js/bundle.js:155146:39)
    at DrawPolygonMode.getAddFeatureAction (http://localhost:3000/static/js/bundle.js:155160:32)
    at DrawPolygonMode.getAddFeatureOrBooleanPolygonAction (http://localhost:3000/static/js/bundle.js:155251:19)
    at DrawPolygonMode.handleClick (http://localhost:3000/static/js/bundle.js:153250:31)
    at EditableGeoJsonLayer.onLayerClick (http://localhost:3000/static/js/bundle.js:161248:28)
    at EditableGeoJsonLayer._onanyclick (http://localhost:3000/static/js/bundle.js:162032:12)
    at EditableGeoJsonLayer._forwardEventToCurrentLayer (http://localhost:3000/static/js/bundle.js:162022:7)
    at EventRegistrar._emit (http://localhost:3000/static/js/bundle.js:344192:9)
    at EventRegistrar.handleEvent (http://localhost:3000/static/js/bundle.js:344090:12)
    at Manager.emit (http://localhost:3000/static/js/bundle.js:311400:20)

Uncaught runtime errors:
×
ERROR
(0 , _bboxPolygon.default) is not a function
TypeError: (0 , _bboxPolygon.default) is not a function
    at DrawRectangleMode.getTwoClickPolygon (http://localhost:3000/static/js/bundle.js:199052:51)
    at DrawRectangleMode.getGuides (http://localhost:3000/static/js/bundle.js:205182:26)
    at DrawRectangleMode.getTentativeGuide (http://localhost:3000/static/js/bundle.js:200606:25)
    at DrawRectangleMode.checkAndFinishPolygon (http://localhost:3000/static/js/bundle.js:205147:35)
    at DrawRectangleMode.handleClick (http://localhost:3000/static/js/bundle.js:205121:12)
    at EditableGeoJsonLayer.onLayerClick (http://localhost:3000/static/js/bundle.js:206738:28)
    at EditableGeoJsonLayer._onanyclick (http://localhost:3000/static/js/bundle.js:207522:12)
    at EditableGeoJsonLayer._forwardEventToCurrentLayer (http://localhost:3000/static/js/bundle.js:207512:7)
    at EventRegistrar._emit (http://localhost:3000/static/js/bundle.js:320708:9)
    at EventRegistrar.handleEvent (http://localhost:3000/static/js/bundle.js:320606:12)

npm ls --depth=0       

├── @deck.gl/core@8.9.36
├── @deck.gl/extensions@8.9.36
├── @deck.gl/layers@8.9.36
├── @deck.gl/mapbox@8.9.36
├── @deck.gl/react@8.9.36
├── @loaders.gl/polyfills@4.2.2
├── @luma.gl/core@8.5.21
├── @luma.gl/webgl@8.5.21
├── @nebula.gl/layers@1.0.2-alpha.1
├── @testing-library/jest-dom@5.17.0
├── @testing-library/react@13.4.0
├── @testing-library/user-event@13.5.0
├── @types/deck.gl__aggregation-layers@ extraneous
├── @types/deck.gl__arcgis@ extraneous
├── @types/deck.gl__carto@ extraneous
├── @types/deck.gl__core@ extraneous
├── @types/deck.gl__extensions@ extraneous
├── @types/deck.gl__geo-layers@ extraneous
├── @types/deck.gl__google-maps@ extraneous
├── @types/deck.gl__json@ extraneous
├── @types/deck.gl__layers@ extraneous
├── @types/deck.gl__mapbox@ extraneous
├── @types/deck.gl__mesh-layers@ extraneous
├── @types/deck.gl__react@ extraneous
├── @types/deck.gl@ extraneous
├── @types/luma.gl__constants@ extraneous
├── @types/luma.gl__core@ extraneous
├── @types/luma.gl__gltools@ extraneous
├── @types/luma.gl__webgl-state-tracker@ extraneous
├── @types/luma.gl__webgl@ extraneous
├── @types/math.gl__core@ extraneous
├── @types/math.gl@ extraneous
├── ajv@8.16.0
├── assert@2.1.0
├── kepler.gl@3.0.0

**Comment by cgcab** [comment]
same problem for me did you find a solution ?
